# Generated by Django 5.0.1 on 2024-02-04 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user_activity",
            new_name="UsersActivity",
        ),
    ]
