# Generated by Django 5.0.1 on 2024-02-04 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_choice_choices_choice_text_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="choices",
            new_name="Choice",
        ),
        migrations.RenameModel(
            old_name="questions",
            new_name="Question",
        ),
        migrations.RenameModel(
            old_name="surveys",
            new_name="Survey",
        ),
        migrations.RenameModel(
            old_name="users",
            new_name="User",
        ),
    ]
