# Generated by Django 5.0.1 on 2024-02-06 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_choice_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersactivity",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="usersactivity",
            options={
                "verbose_name": "Активность пользователя",
                "verbose_name_plural": "Активность пользователей",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="parent_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.question",
            ),
        ),
        migrations.AddField(
            model_name="usersactivity",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
