# Generated by Django 5.0.1 on 2024-02-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_usersactivity_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="next_question",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_choices",
                to="main.question",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="main.question",
            ),
        ),
    ]
