# Generated by Django 5.0.1 on 2024-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_choice_next_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="specifics",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="survey_title",
        ),
        migrations.AddField(
            model_name="survey",
            name="text",
            field=models.CharField(
                default=str, max_length=255, verbose_name="Название"
            ),
            preserve_default=False,
        ),
    ]
