# Generated by Django 5.0.1 on 2024-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_choice_text_choice_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersactivity",
            name="user_id",
            field=models.CharField(max_length=40),
        ),
    ]
