# Generated by Django 5.0.1 on 2024-02-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_usersactivity_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="parent_question",
        ),
        migrations.AddField(
            model_name="question",
            name="start",
            field=models.BooleanField(default=False, verbose_name="Начало опроса"),
        ),
    ]
