# Generated by Django 5.0.1 on 2024-02-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_question_parent_question_question_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="first_question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_survey",
                to="main.question",
                verbose_name="Первый вопрос",
            ),
        ),
    ]
