# Generated by Django 5.0.1 on 2024-02-10 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_survey_first_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="start",
        ),
    ]
